### ISSUE TITLE
current status of provided configs

### ISSUE THREAD

**Issue by pitrack** [jsalt18-sentence-repl/jiant#325]
Before release, we probably want to ensure all the `major experiment scripts` and defaults will run out/start training of the box (related to #296), or making it clear that it's a template (`_tmpl`) or `_bare` and needs to be extended upon. Before release, we may also need to add more flags? 

Before branch, we should make sure we didn't accidentally break anything in the past couple of days as we tried to get results.

There may be some benign environment variables/checkpoint/preproc files that are causing these issues - please edit this section if they run correctly for you.

✅ `defaults.conf`
✅ `demo.conf` 
✅ `edgeprobe_bare.conf` 
✅  `edgeprobe_demo.conf` 
✅   `edgeprobe_existing.conf` 
❓     `edgeprobe_train.conf`
✅   `eval_existing.conf`
✅    `final.conf`
✅   `final_xl.conf`
✅  `test_run.conf`
❓  `weighting.conf`

❓ Major experiment scripts -- tracked by #296?

For `defaults.conf`, `final.conf`, `final_xl.conf`, `test_run.conf` have this error, but I believe it is appropriately documented (setting the risky flag as suggested leads to a successful run)

```
$ python main.py --config_file config/defaults.conf
[...]
08/02 04:01:47 PM: Total number of parameters: 159677554 (1.59678e+08)
08/02 04:01:47 PM: Number of trainable parameters: 141639698 (1.4164e+08)
08/02 04:01:47 PM:      Finished building model in 2.294s
08/02 04:01:47 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    main(sys.argv[1:])
  File "main.py", line 179, in main
    "If you're pretraining on a task you plan to reuse as a target task, set\n"
  File "/home/pitrackx_gmail_com/jiant/src/utils.py", line 1106, in assert_for_log
    assert condition, error_message
AssertionError: If you're pretraining on a task you plan to reuse as a target task, set
allow_reuse_of_pretraining_parameters = 1(risky), or train in two steps:
  train with do_train = 1, train_for_eval = 0, stop, and restart with
  do_train = 0 and train_for_eval = 1.
Traceback (most recent call last):
  File "main.py", line 326, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 316, in <module>
    main(sys.argv[1:])
  File "main.py", line 179, in main
    "If you're pretraining on a task you plan to reuse as a target task, set\n"
  File "/home/pitrackx_gmail_com/jiant/src/utils.py", line 1106, in assert_for_log
    assert condition, error_message
AssertionError: If you're pretraining on a task you plan to reuse as a target task, set
allow_reuse_of_pretraining_parameters = 1(risky), or train in two steps:
  train with do_train = 1, train_for_eval = 0, stop, and restart with
  do_train = 0 and train_for_eval = 1.
```
For `weighting.conf` 
```
08/02 05:40:12 PM: task.n_train_examples: [('cola', 8551), ('mnli', 392702), ('mrpc', 3668), ('qnli', 108436), ('qqp', 363849), ('rte', 2490), ('sst', 67349), ('sts-b', 5749), ('wnli', 635)]
08/02 05:40:12 PM: weighting_method: none
08/02 05:40:12 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    main(sys.argv[1:])
  File "main.py", line 209, in main
    args.shared_optimizer, args.load_model, phase="main")
  File "/home/pitrackx_gmail_com/jiant/src/trainer.py", line 386, in train
    normalized_sample_weights  = [i/sum(sample_weights) for i in sample_weights]
UnboundLocalError: local variable 'sample_weights' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 326, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 316, in <module>
    main(sys.argv[1:])
  File "main.py", line 209, in main
    args.shared_optimizer, args.load_model, phase="main")
  File "/home/pitrackx_gmail_com/jiant/src/trainer.py", line 386, in train
    normalized_sample_weights  = [i/sum(sample_weights) for i in sample_weights]
UnboundLocalError: local variable 'sample_weights' referenced before assignment
```

**Comment by shuningjin** [comment]
I have changed <weighting.conf> and it should work now.
(Previously weighting_method is set to none, which requires explicit overwrite, otherwise error will be raised. Now it is given a default value.)
